spring.mvc.servlet.path=/
logging.level.com.baosight=info
spring.main.allow-bean-definition-overriding=true
server.port=8083
spring.mvc.view.suffix=.jsp
spring.mvc.view.prefix=/**
projectEnv=DEV

projectName=demo
componentEname=ep
moduleName=DN
platSchema=iplat4j

enterpriseName=\u5b9d\u4fe1\u8f6f\u4ef6\u5e73\u53f0\u7814\u7a76\u4e00\u6240
customerName=\u4e2d\u56fd\u5b9d\u6b66\u94a2\u94c1\u96c6\u56e2\u6709\u9650\u516c\u53f8

datasource.type=dbcp

jdbc.driverClassName=com.gbasedbt.jdbc.Driver
jdbc.url=jdbc:gbasedbt-sqli://<gbase-host>:<gbase-port>/<db-name>:GBASEDBTSERVER=<gbase-server>;SQLMODE=Oracle;DB_LOCALE=zh_cn.utf8;APPENDISAM=TRUE;NON_QUOTATION_COLUNAME_ALIAS_UPPERCASE_FORCE=Y;DELIMIDENT=Y;
jdbc.username=<db-username>
jdbc.password=<db-password>
jdbc.maxActive=50
jdbc.validationQuery=SELECT 1 FROM ${platSchema}.TEDFA00

configEx=xservices;xservice.security;xservices.job;xservices.message;xservices.bpm;

iplat.core.cache.redisExpireTime=200000
