spring.mvc.servlet.path=/
spring.main.allow-bean-definition-overriding=true
spring.mvc.view.suffix=.jsp
spring.mvc.view.prefix=/**
server.port=8083

projectName=demo
componentEname=ep
projectEnv=dev
moduleName=DN
platSchema=iplat4j

enterpriseName=\u5b9d\u4fe1\u8f6f\u4ef6\u8f68\u9053\u4ea4\u901a\u4e8b\u4e1a\u672c\u90e8\u667a\u6167\u7ebf\u7f51\u4e8b\u4e1a\u90e8
customerName=\u91cd\u5e86\u5e02\u8f68\u9053\u4ea4\u901a\uff08\u96c6\u56e2\uff09\u6709\u9650\u516c\u53f8

datasource.type=dbcp

jdbc.driverClassName=com.gbasedbt.jdbc.Driver
jdbc.url=jdbc:gbasedbt-sqli://<gbase-host>:<gbase-port>/<db-name>:GBASEDBTSERVER=<gbase-server>;SQLMODE=Oracle;DB_LOCALE=zh_cn.utf8;APPENDISAM=TRUE;NON_QUOTATION_COLUNAME_ALIAS_UPPERCASE_FORCE=Y;DELIMIDENT=Y;
jdbc.username=<db-username>
jdbc.password=<db-password>
jdbc.maxActive=20
jdbc.validationQuery=SELECT 1 FROM ${platSchema}.TEDFA00

configEx=xservices;xservice.security;xservices.job;xservices.message;xservices.bpm;
