spring.mvc.servlet.path=/
spring.main.allow-bean-definition-overriding=true
spring.mvc.view.suffix=.jsp
spring.mvc.view.prefix=/**
server.port=8083

projectName=demo
componentEname=demo-web
projectEnv=prod
platSchema=iplat4j

jdbc.driverClassName=com.dm.jdbc.driver.DmDriver
jdbc.url=jdbc:dm://<dm-host>:<dm-port>/<db-name>
jdbc.username=<db-username>
jdbc.password=<db-password>
jdbc.maxActive=10
jdbc.validationQuery=SELECT 1

configEx=iplat4j;xservices;
