spring.mvc.servlet.path=/
spring.main.allow-bean-definition-overriding=true
spring.mvc.view.suffix=.jsp
spring.mvc.view.prefix=/**
server.port=8083

projectName=demo
componentEname=ep
projectEnv=prod
moduleName=DN
platSchema=iplat4j

datasource.type=dbcp

jdbc.driverClassName=com.gbasedbt.jdbc.Driver
jdbc.url=jdbc:gbasedbt-sqli://<gbase-host>:<gbase-port>/<db-name>:GBASEDBTSERVER=<gbase-server>;SQLMODE=Oracle;DB_LOCALE=zh_cn.utf8;APPENDISAM=TRUE;NON_QUOTATION_COLUNAME_ALIAS_UPPERCASE_FORCE=Y;DELIMIDENT=Y;
jdbc.username=<db-username>
jdbc.password=<db-password>
jdbc.maxActive=20
jdbc.validationQuery=SELECT 1 FROM ${platSchema}.TEDFA00

configEx=xservices;xservice.security;xservices.job;xservices.message;xservices.bpm;
